### ISSUE TITLE
jagsUI masks View : causing issues with Rstudio dataviewer

### ISSUE THREAD

**Issue by OliverFishCode** [kenkellner/jagsUI#24]
This issue was mention in  Issue #13. This is still very annoying. Is there a workaround or can you implement a solution?

**Comment by kenkellner** [comment]
You can save Rstudio's custom View() implementation to a new name before you load jagsUI

```r
rstudio_view <- View
library(jagsUI)
View(iris)
rstudio_view(iris)
```

I'm still not convinced this isn't mainly an Rstudio problem, since Rstudio is silently overwriting utils::View with its own function when you launch R from the IDE.

It seems like you can detect if you are in an RStudio environment with

```
Sys.getenv("RSTUDIO")
```
so maybe this could be handled automatically by jagsUI. Changing package functions to handle specific IDEs isn't ideal though and there's no guarantee that check will work long-term.

**Comment by OliverFishCode** [comment]
This should work. Additionally, I understand that changing package functions for a bunch of specific IDE's would be a pain. However, Rstudio I would consider the exception, as it is the most commonly used IDE for R.

**Comment by kenkellner** [comment]
I plan to replace the `View` method approach with a standalone function in the next version of the package, see 275108c. For now (in 1.5.1) it gives a warning that `View` is deprecated.
