### ISSUE TITLE
verbose messages for autojags()

### ISSUE THREAD

**Issue by cring-toxstrategies** [kenkellner/jagsUI#25]
Wishlist item: if autojags() could provide the same kind of detailed progress bars that jags() does, i.e. showing progress of adaptation, burn-in, and sampling. Information on adaptation would be particularly nice to have -- including how many adaptation iterations were performed and whether adaptation was sufficient (especially if adaptation is automated to repeat until either JAGS reports it was sufficient or a max number of adaptation iterations is reached).

**Comment by kenkellner** [comment]
Do you mean a set of progress bars for each individual increment that runs? I've experimented with that in the past but it really clogs up the console if you have a lot of increments. I can revisit though.

You can't really have an overall progress bar since we don't know ahead of time what the "final" number of iterations will be.

**Comment by cring-toxstrategies** [comment]
I was thinking of a set of progress bars for each increment, but I see what you mean about clogging up the console. Even a message saying something like "Adaptation phase .... adaptation complete after 2000 iterations" or "Adaptation phase .... adaptation not complete at maximum of 10,000 iterations" would be nice. Just to keep an eye on whether the model is in adaptation, burn-in, or sampling phase, and get a sense of how long each is taking. I realize the final jagsUI object contains info on adaptation iterations and completeness, but I get antsy during long-running models to know whether adaptation is taking a lot of iterations, or whether adaptation finished quickly and sampling is taking a long time in the first increment.

**Comment by kenkellner** [comment]
Makes sense. I'm in the middle of a pretty comprehensive re-write of the code so it's a good time to make these kind of adjustments.

In the next version I am leaning towards removing the auto-adapt functionality, as it can cause some weird issues where different chains adapt for different amounts of time. In that scenario you would know how many adapt iterations were going to happen (because you either set it or left it at the default of 1000). But as you said it would still be nice to know which phase you were on in a given increment.
