### ISSUE TITLE
Problem running parallel on multiple cores

### ISSUE THREAD

**Issue by zormer23** [kenkellner/jagsUI#4]
Hello!  I've been running jagsUI for several months now, and only recently decided I needed to run on multiple cores to speed things up.  I'm running jagsUI 1.3.1 in R3.2.0 on Mac OSX.  This command has always worked:  

out.jagsUI <- jags(data, inits, params, model_file, nc, na, ni, nb, nt)

If I change nothing, but add the parallel=TRUE option:
out.jagsUI <- jags(data, inits, params, model_file, nc, na, ni, nb, nt, parallel=TRUE)

I get this error:
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: could not find function "set.modules"

for the 3 chains I'm trying to run.

It seems that some package is not being loaded in the 3 parallel instantiations of R, but I can't find what package that might be, and if I knew I would know how to get jagsUI to load it... am I on the right track?
Thanks!
Rich

**Comment by kenkellner** [comment]
Hi Rich,

Sorry you are having trouble, and thanks for getting in touch. 

You're right that a function is not being properly loaded into the parallel subprocesses. Set.modules() is actually a behind-the-scenes function in jagsUI itself so there's not much you could do yourself to force it to load.

My first suggestion is to update jagsUI to the most current version (v1.3.7) which is available on Github or from CRAN. Also double check to make sure that the version of rjags you have is at least version 3-13. There were a lot of issues with parallel processing that I've fixed since v1.3.1 was released so it's possible that your issue is related  to one of those.

If this doesn't fix your issue, I can take a closer look - often the easiest way to do that is for you to send over the analysis code (and data, if appropriate) that isn't working so I can try to recreate the problem myself.

Ken

**Comment by genwei007** [comment]
Hi Ken,

I have a question about doing parallel. Say, if I command load.module("glm") in R (or other JAGS modules), will jagsUI know this when running parallel chains? I am always not sure if it is really doing what I commanded. Thanks.

CW

**Comment by kenkellner** [comment]
Use the "modules" argument built-in to the jags() function in jagsUI (see ?jags) to specify which modules you want to load. These modules will be carried over into each parallel process. If you call load.modules() yourself (a function from the rjags package) your module settings will not be applied to each separate process. Note that by default jagsUI loads the glm module unless you specifically tell it not to.

**Comment by zormer23** [comment]
Ken - Thanks for taking the time to respond so quickly.  I updated version as you suggested, but still had the problem.  Eventually, I grew to suspect that, because I had been installing packages in a user-defined directory, maybe that was the problem.  After re-installing everything in the default directory, it appears to be working.  Perhaps for other users your script could be modified to use packages stored in any of the  the path in .libPaths()  ?  Or not ... sounds like potentially a big change?  Regardless, I'm in good shape now.  Thanks again...  Regards, Rich

**Comment by kenkellner** [comment]
Rich - That's interesting. I haven't done any testing with installing to a user-defined directory. That gives me a place to start though - I'll see if I can re-create your problem and find a way to fix it. Glad it's working in some for now.

Thanks, Ken

**Comment by zormer23** [comment]
Ken – One more question.  When I kick off parallel chains using jagsUI on a PC, the PC’s Windows Task Manager will show the CPU usage by the three process on their individual cores, each of which is always less than 25%.  Do you know of any ways to utilize more of the CPU on each of the cores?

Thanks,
Rich

Richard B. Mrozinski
Lecturer and Graduate Research Assistant
Borderlands Research Institute
Department of Natural Resources
Sul Ross State University
(832) 228-7130
rbm14fk@sulross.edu

**Comment by kenkellner** [comment]
Rich,

My understanding is that the percentage you are seeing in Windows is relative to the entire capacity of the CPU (i.e., all cores pooled together). I assume you have a quad-core processor; thus when you run 3 parallel chains, you are using 3 cores, each of which use at or near 1/4 of the total CPU (=25%). You can test this in a crude way by running 4 chains instead - my guess is that everything else you try to do on the computer will grind to a halt because 4x25% = 100% of the CPU will be used by JAGS.

**Comment by zormer23** [comment]
Ah ok that makes sense… Thanks for your speedy reply!

Rich

Richard B. Mrozinski
Lecturer and Graduate Research Assistant
Borderlands Research Institute
Department of Natural Resources
Sul Ross State University
(832) 228-7130
rbm14fk@sulross.edu

**Comment by MTHallworth** [comment]
Hi Ken, 

I'm having a similar issue described above re: set.modules when jagsUI is located in a user define library. I receive the following error message when I run the model in parallel. 

[1] "2016-08-12 11:31:49 EDT"
Processing function input....... 
Done. 
 
Beginning parallel processing using 3 cores. Console output will be suppressed.
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: could not find function "set.modules"
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors

I'm running the analysis on a supercomputer because it requires a lot of RAM and don't have write privileges to the default R library folder. I'd prefer to use jagsUI instead of other jags wrapper packages. Any information on how to 1) create a workaround or 2) solve this issue would be greatly appreciated. My session information is posted below. 

Thanks in advance,

Mike

sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)
locale:
 [1] LC_CTYPE=en_US.iso885915       LC_NUMERIC=C                  
 [3] LC_TIME=en_US.iso885915        LC_COLLATE=en_US.iso885915    
 [5] LC_MONETARY=en_US.iso885915    LC_MESSAGES=en_US.iso885915   
 [7] LC_PAPER=en_US.iso885915       LC_NAME=C                     
 [9] LC_ADDRESS=C                   LC_TELEPHONE=C                
[11] LC_MEASUREMENT=en_US.iso885915 LC_IDENTIFICATION=C           
attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  base     
other attached packages:
[1] abind_1.4-5     jagsUI_1.4.2    lattice_0.20-33 rjags_4-6      
[5] coda_0.18-1    
loaded via a namespace (and not attached):
[1] grid_3.2.1    methods_3.2.1

**Comment by kenkellner** [comment]
Hi Mike,

Could you give me a little more information about your setup? Specifically, which of the packages listed in sessionInfo() are located in your user defined library, and which are in the default library(s). Also, when you installed jagsUI to your user defined library, how exactly did you do it, and how do you attach the library when you want to use it, exactly? (e.g: library(jagsUI, lib.loc='path/to/my/library')?

Ken

**Comment by MTHallworth** [comment]
Hi Ken, 

Thanks for looking into this. All the packages that I use on the server are located in a user-defined library. Below is a bit of code for how I first get the packages on the server. I move the tar.gz files over and then install the packages. 

```
install.packages("/home/hallworthm/CostOfRepro/rjags_4-6.tar.gz", repos = NULL, type="source",lib="/home/hallworthm/CostOfRepro",configure.args="--enable-rpath")

install.packages("/home/hallworthm/CostOfRepro/jagsUI_1.4.2.tar.gz", repos = NULL, type="source",lib="/home/hallworthm/CostOfRepro")
```

I set my library location to my user folder on the server and load the packages.
```

.libPaths("/home/hallworthm/CostOfRepro")

library(parallel,lib.loc="/home/hallworthm/CostOfRepro")
library(rjags,lib.loc="/home/hallworthm/CostOfRepro")
library(jagsUI,lib.loc="/home/hallworthm/CostOfRepro")
library(abind,lib.loc="/home/hallworthm/CostOfRepro")

```
I use the following to run the model. The small number of iterations is just a trial run to get it working on the server. 
```
a<-Sys.time()
Sys.time()
M<-jagsUI::jags(model = "CostOfRepro_copy.txt",
                module = c('glm'),
                codaOnly = params,
                data = win.data,
                inits = inits,
                n.adapt = 2,
                n.chains = 3, 
                n.iter = 10, 
                n.thin = 1,
                n.burn = 0,
                parallel = TRUE,
                DIC = FALSE,
                parameters.to.save = params)
Sys.time()
Sys.time()-a
```
Let me know if you need any additional information. Thanks again. 

Mike

**Comment by kenkellner** [comment]
@MTHallworth I think 68af7ae  may fix your problem by importing your current list of library paths to all clusters. I suggest making sure all the default package directories are also included in your path (in addition to your custom library) just to be safe:

```
my.path <- 'path/to/my/library'
.libPaths(c(my.path,.libPaths()))
```

Can you give the latest Github version a shot and see if it works?

@zormer23 Hopefully this fixes your issue as well.

**Comment by MTHallworth** [comment]
Great - that update worked on my end. The model is running on the server now in parallel. Thanks for taking a look. It takes forever to run but it didn't crash on set.modules. 

Thanks again.

**Comment by kenkellner** [comment]
Excellent - if you run into any additional issues let me know.
