### ISSUE TITLE
Issue with print() of a jags output object

### ISSUE THREAD

**Issue by cmoore99** [kenkellner/jagsUI#42]
I have used jagsUI a lot the last couple of years (and it's great!), but I came across an issue that has me stumped.  I produced an output object from the jags function, but print() or jags.View() displays the values of one node incorrectly.  The values should all be non-zero (the node is just the inverse of another node), but they appear as 0 under either of the print functions.  Directly accessing the node, however, results in the correct values being displayed.

I have attached a script that demonstrates the issue, along with a file that contains the jags output object (both contained in a .zip archive).  I can provide the full code that generates the output, but I'm hoping that all that is needed is contained here.  Thanks for your attention, and I'll be happy to find out it's something dumb on my end.

Clint Moore
[jagsUI.printproblem.zip](https://github.com/kenkellner/jagsUI/files/5368922/jagsUI.printproblem.zip)

**Comment by kenkellner** [comment]
Hi Clint,

It looks like I can print the correct values if I increase the number of digits in the print call, e.g.

```r
print(out, digits=10)
```

This is not totally satisfying though because when you just call `print(out)` you do see plenty of digits, they're just all 0. Values must be being rounded to zero and then being converted to scientific notation. I'll look into it.
