### ISSUE TITLE
Allow fine control of factory modules

### ISSUE THREAD

**Issue by genwei007** [kenkellner/jagsUI#9]
Hi,

How to turn off TemperedMix using jags function of jagsUI? The "the mix module" in the manual says how to do in JAGS itself, but I have no idea how to do it in jagsUI. Thanks.

**Comment by kenkellner** [comment]
Hi,

jagsUI does not currently have this functionality (i.e., manual control of factories), though I would like to add it when I get some time to implement and test.

You might try package runjags in the meantime, which does allow this level of fine control. Also, since jagsUI is calling rjags functions, it's possible that setting factories in rjags (as per the manual) would also change them for jagsUI (but I doubt it).

**Comment by kenkellner** [comment]
Commit db876a0 adds this functionality for `jags()`, `autojags()`, and `jagsbasic()` with the new `factories` argument. To turn off TemperedMix you would specify `factories='mix::TemperedMix sampler FALSE'`, assuming you had loaded the `mix` module with the `modules` argument. If you'd like to test this, I'd greatly appreciate any feedback.
